apiVersion: v1
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: {{ .Release.Name }}-front-cm
data:
  BACKEND_URL: "mysql://root:@{{ .Release.Name }}-mysql-svc.{{ .Release.Namespace }}.svc.cluster.local:3306/tribeshomestay"
