apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-front-svc
  labels:
    app: {{ .Release.Name }}-front-svc
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8000
      protocol: TCP
      name: http
    - port: 443
      targetPort: 8000
      protocol: TCP
      name: https
  selector:
    app: {{ .Release.Name }}-web
status:
  loadBalancer: {}
